# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/duya25446/luckfox_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/duya25446/luckfox_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duya25446/luckfox_lib/CMakeFiles /home/duya25446/luckfox_lib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duya25446/luckfox_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lib_src

# Build rule for target.
lib_src: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib_src
.PHONY : lib_src

# fast build rule for target.
lib_src/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/build
.PHONY : lib_src/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

lib/src/lcd.o: lib/src/lcd.c.o
.PHONY : lib/src/lcd.o

# target to build an object file
lib/src/lcd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lcd.c.o
.PHONY : lib/src/lcd.c.o

lib/src/lcd.i: lib/src/lcd.c.i
.PHONY : lib/src/lcd.i

# target to preprocess a source file
lib/src/lcd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lcd.c.i
.PHONY : lib/src/lcd.c.i

lib/src/lcd.s: lib/src/lcd.c.s
.PHONY : lib/src/lcd.s

# target to generate assembly for a file
lib/src/lcd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lcd.c.s
.PHONY : lib/src/lcd.c.s

lib/src/lcd_init.o: lib/src/lcd_init.c.o
.PHONY : lib/src/lcd_init.o

# target to build an object file
lib/src/lcd_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lcd_init.c.o
.PHONY : lib/src/lcd_init.c.o

lib/src/lcd_init.i: lib/src/lcd_init.c.i
.PHONY : lib/src/lcd_init.i

# target to preprocess a source file
lib/src/lcd_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lcd_init.c.i
.PHONY : lib/src/lcd_init.c.i

lib/src/lcd_init.s: lib/src/lcd_init.c.s
.PHONY : lib/src/lcd_init.s

# target to generate assembly for a file
lib/src/lcd_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lcd_init.c.s
.PHONY : lib/src/lcd_init.c.s

lib/src/lib_gpio.o: lib/src/lib_gpio.c.o
.PHONY : lib/src/lib_gpio.o

# target to build an object file
lib/src/lib_gpio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_gpio.c.o
.PHONY : lib/src/lib_gpio.c.o

lib/src/lib_gpio.i: lib/src/lib_gpio.c.i
.PHONY : lib/src/lib_gpio.i

# target to preprocess a source file
lib/src/lib_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_gpio.c.i
.PHONY : lib/src/lib_gpio.c.i

lib/src/lib_gpio.s: lib/src/lib_gpio.c.s
.PHONY : lib/src/lib_gpio.s

# target to generate assembly for a file
lib/src/lib_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_gpio.c.s
.PHONY : lib/src/lib_gpio.c.s

lib/src/lib_spi.o: lib/src/lib_spi.c.o
.PHONY : lib/src/lib_spi.o

# target to build an object file
lib/src/lib_spi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_spi.c.o
.PHONY : lib/src/lib_spi.c.o

lib/src/lib_spi.i: lib/src/lib_spi.c.i
.PHONY : lib/src/lib_spi.i

# target to preprocess a source file
lib/src/lib_spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_spi.c.i
.PHONY : lib/src/lib_spi.c.i

lib/src/lib_spi.s: lib/src/lib_spi.c.s
.PHONY : lib/src/lib_spi.s

# target to generate assembly for a file
lib/src/lib_spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_spi.c.s
.PHONY : lib/src/lib_spi.c.s

lib/src/lib_uart.o: lib/src/lib_uart.c.o
.PHONY : lib/src/lib_uart.o

# target to build an object file
lib/src/lib_uart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_uart.c.o
.PHONY : lib/src/lib_uart.c.o

lib/src/lib_uart.i: lib/src/lib_uart.c.i
.PHONY : lib/src/lib_uart.i

# target to preprocess a source file
lib/src/lib_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_uart.c.i
.PHONY : lib/src/lib_uart.c.i

lib/src/lib_uart.s: lib/src/lib_uart.c.s
.PHONY : lib/src/lib_uart.s

# target to generate assembly for a file
lib/src/lib_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lib_src.dir/build.make CMakeFiles/lib_src.dir/lib/src/lib_uart.c.s
.PHONY : lib/src/lib_uart.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lib_src"
	@echo "... main"
	@echo "... lib/src/lcd.o"
	@echo "... lib/src/lcd.i"
	@echo "... lib/src/lcd.s"
	@echo "... lib/src/lcd_init.o"
	@echo "... lib/src/lcd_init.i"
	@echo "... lib/src/lcd_init.s"
	@echo "... lib/src/lib_gpio.o"
	@echo "... lib/src/lib_gpio.i"
	@echo "... lib/src/lib_gpio.s"
	@echo "... lib/src/lib_spi.o"
	@echo "... lib/src/lib_spi.i"
	@echo "... lib/src/lib_spi.s"
	@echo "... lib/src/lib_uart.o"
	@echo "... lib/src/lib_uart.i"
	@echo "... lib/src/lib_uart.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

